\newpage 

`r if (knitr:::is_html_output()) '# References'`
`r if (!knitr:::is_html_output()) '# References'`

```{r files, include=FALSE}
if(!dir.exists("files"))
  {dir.create("files")}
if(exists("fb"))
  {openxlsx::write.xlsx(fb,"files/data.xlsx")}
if(dir.exists("docs"))
  {zip::zipr(zipfile = "docs/files.zip", files = "files")}
```

```{r packagas, eval=FALSE, include=FALSE}

install.packages("devtools")
install.packages("bookdown")
install.packages("citr")
install.packages("knitr")
install.packages("tidyverse")
install.packages("googlesheets4")
install.packages("agricolae")
install.packages("GerminaR")
install.packages("compareGroups")
install.packages("FactoMineR")
install.packages("cowplot")
install.packages("grid")
install.packages("png")
install.packages("jpeg")

devtools::install_github("lbusett/insert_table")
devtools::install_github("flavjack/GerminaR")

source("cnfg/setup.r")
knitr::write_bib(c(.packages()),'cnfg/pkgs.bib')

```

```{r eval=FALSE, include=FALSE}
# # re-write local files with git hub
# git fetch --all
# git reset --hard origin/master
# git pull origin master
# 
# # Undoing Multiple Commits
# git reset --hard hss
# 
# # Force push 
# git push -f origin master
```
